### PR TITLE
Sample API tokenisation

### PR DESCRIPTION
**Pull request by VigneshKarthigeyan**
Key for the token is 'secretkey'

### CODE REVIEW

**Comment by tamilarasumk731** [comment]
@VigneshKarthigeyan Can you move the Keyrequired function to separate file. And Import the function alone in app.py
CC: @AkbarHabeeb @InbasasiS @smartsri18

**Comment by VigneshKarthigeyan** [comment]
Will do bro

**Comment by tamilarasumk731** [comment]
@VigneshKarthigeyan There are some conflicts in your code. Can you please take a pull from dev branch and resolve the conflicts and push

**Comment by VigneshKarthigeyan** [comment]
@tamilarasumk731 Anna I have resolved some conflicts.Can you please check on those commits?

**Comment by AkbarHabeeb** [comment]
> @VigneshKarthigeyan Can you move the Keyrequired function to separate file. And Import the function alone in app.py
> CC: @AkbarHabeeb @InbasasiS @smartsri18

Good step @tamilarasumk731 

Post the completion of the task, update on the trello card with the PR link.

**Comment by AkbarHabeeb** [comment]
@VigneshKarthigeyan Testing now

**Comment by AkbarHabeeb** [comment]
Merged

**Pull request merged**
